# Generated by Django 5.0.1 on 2024-06-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipename', models.CharField(max_length=20)),
                ('recipedesc', models.CharField(max_length=50)),
                ('ingredients', models.CharField(max_length=200)),
                ('procedure', models.CharField(max_length=500)),
            ],
        ),
    ]
