# Generated by Django 5.0.1 on 2024-06-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrecipe',
            name='recipeimage',
            field=models.ImageField(default='', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='newrecipe',
            name='procedure',
            field=models.CharField(max_length=1000),
        ),
    ]
