# Generated by Django 5.0.1 on 2024-06-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_newrecipe_recipeimage_alter_newrecipe_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newrecipe',
            name='recipeimage',
            field=models.ImageField(upload_to='media'),
        ),
    ]
