# Generated by Django 5.0.1 on 2024-06-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_newrecipe_recipeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newrecipe',
            name='ingredients',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newrecipe',
            name='procedure',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newrecipe',
            name='recipedesc',
            field=models.TextField(),
        ),
    ]
