# Generated by Django 5.0.1 on 2024-06-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_newrecipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newrecipe',
            name='recipeimage',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
